"""Script for migrations_two

Revision ID: 50c8e87c9ccf
Revises: fe265415a12e
Create Date: 2024-12-10 16:06:05.214407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c8e87c9ccf'
down_revision: Union[str, None] = 'fe265415a12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_packages', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_packages', 'name')
    # ### end Alembic commands ###
