"""Script for migrations

Revision ID: fe265415a12e
Revises: 
Create Date: 2024-12-10 15:22:22.674260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe265415a12e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_packages', sa.Column('date_created', sa.DateTime(), nullable=True))
    # Add the USING clause to handle the type conversion
    op.execute('ALTER TABLE flight_packages ALTER COLUMN departure_date TYPE DATE USING departure_date::date')
    op.execute('ALTER TABLE flight_packages ALTER COLUMN return_date TYPE DATE USING return_date::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight_packages', 'return_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('flight_packages', 'departure_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('flight_packages', 'date_created')
    # ### end Alembic commands ###
