# Generated by Django 5.1.4 on 2024-12-16 15:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', django_ckeditor_5.fields.CKEditor5Field()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='flightpackage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flightpackage',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('economy_plus', 'Economy Plus'), ('business', 'Business'), ('first_class', 'First Class')], default='economy', max_length=255),
        ),
        migrations.AddField(
            model_name='flightpackage',
            name='flight_mode',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi City')], default='one_way', max_length=255),
        ),
        migrations.AddField(
            model_name='flightpackage',
            name='placeholder_image',
            field=models.ImageField(default='https://placehold.co/600x400/000000/FFFFFF.svg', upload_to='flight_images'),
        ),
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_passengers', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=255)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightpackage')),
            ],
        ),
    ]
