# Generated by Django 5.1.4 on 2025-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_bookingapplication_is_hidden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingapplication',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='bookingapplication',
            name='last_name',
            field=models.CharField(default='lastName', max_length=255),
            preserve_default=False,
        ),
    ]
